import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";
import { TProduct } from "../../types/products";

function ProductDetailsPage({ product }: { product: TProduct }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Product {`${product?.id}`}</h1>

        <div className={styles.grid}>
          {!!product?.id && (
            <section key={product.id} className={styles.card}>
              <h2>{product.title}</h2>
              <Image
                alt={product.description}
                src={product.images[0]}
                width={100}
                height={100}
              />
              <p>{product.description}</p>
            </section>
          )}
        </div>
      </main>
    </div>
  );
}

export default ProductDetailsPage;
